Rails Blog Views
ezraermy/rails-blog pull request #6
Opened 2023-08-23 22:51 UTC by ezraermy

In this pull request, I:
- Created a view file for each model.
- Used preprocessed HTML file with embedded Ruby code.
- Used layouts and templates for shared content.

### Other requirements 
- No linter errors
- Document professional way
- Follow gitflow

2023-08-23 23:55 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @ezraermy  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/93520178/261856220-b94908ad-80bf-4dc0-b50f-e65f429c0400.gif)


## Highlights
- [x] Green linters check :heavy_check_mark: 
- [x] Nice use of partials :+1: 
- [x] The views respect the wireframes given :+1: 

## Required Changes ♻️
_Check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and :computer: Happy coding :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 23:55 UTC, laiifuu commented on app/views/shared/_comments.html.erb
> +</ul>
There are a couple of issues with this view: 
- The list of comment objects are being rendered after the list of comments that are properly listed: 
![image](https://github.com/ezraermy/rails-blog/assets/93520178/ea04d54e-f326-42e8-aa94-ceeaf67bce5a)
- The list of comments in the user's `show` view should only list the last 5 comments added to the post ( the result of the recent_comments method in the Post model ). As you can see in the previous image, 8 comments are being shown. 
- The number of comments at the top is not being updated.

2023-08-23 23:55 UTC, laiifuu commented on app/views/shared/_user.html.erb
> +    <p>Number of posts: <%= if user.posts.any? then user.postCounter else 0 end %></p>
The number of posts is not being displayed correctly, I created multiple posts for this user, and yet 0 is being displayed: 
![image](https://github.com/ezraermy/rails-blog/assets/93520178/b4163632-a83e-4576-8eda-b6805478f632)

2023-08-25 15:39 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 15:41 UTC, merged